### ISSUE TITLE
maven central not release 0.2.15 and 0.2.16 versions

### ISSUE THREAD

**Issue by dyrnq** [wz2cool/canal-utils#27]
- <https://mvnrepository.com/artifact/com.github.wz2cool/canal-utils>

**Comment by wz2cool** [comment]
will fix this issue

**Comment by wz2cool** [comment]
昨天发了 但是同步到maven 估计要点时间

下面oss 已经能看到了
https://repo1.maven.org/maven2/com/github/wz2cool/canal-utils/0.2.16/

**Comment by wz2cool** [comment]
完成同步 
关闭issue

https://search.maven.org/artifact/com.github.wz2cool/canal-utils/0.2.16/jar?eh=
